name: C CI

on:
  push: 
   branches:
      - 'master'
  pull_request:
    types: 
      -opened

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./challenge08/
      run: make all